# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_info/Info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Info(genpy.Message):
  _md5sum = "9e754eb821b149031ec48f77a9ecbbc4"
  _type = "robot_info/Info"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
float32 voltage
float64 orientation
float64 velocity
int32 motor_status
float64[] sonar_status
float64[] arm_torque
int32 arm_status
int32 cam360_status
int32 second_cam_status
int32 map_status
int32 ptz_camera
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','voltage','orientation','velocity','motor_status','sonar_status','arm_torque','arm_status','cam360_status','second_cam_status','map_status','ptz_camera']
  _slot_types = ['std_msgs/Header','float32','float64','float64','int32','float64[]','float64[]','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,voltage,orientation,velocity,motor_status,sonar_status,arm_torque,arm_status,cam360_status,second_cam_status,map_status,ptz_camera

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.voltage is None:
        self.voltage = 0.
      if self.orientation is None:
        self.orientation = 0.
      if self.velocity is None:
        self.velocity = 0.
      if self.motor_status is None:
        self.motor_status = 0
      if self.sonar_status is None:
        self.sonar_status = []
      if self.arm_torque is None:
        self.arm_torque = []
      if self.arm_status is None:
        self.arm_status = 0
      if self.cam360_status is None:
        self.cam360_status = 0
      if self.second_cam_status is None:
        self.second_cam_status = 0
      if self.map_status is None:
        self.map_status = 0
      if self.ptz_camera is None:
        self.ptz_camera = 0
    else:
      self.header = std_msgs.msg.Header()
      self.voltage = 0.
      self.orientation = 0.
      self.velocity = 0.
      self.motor_status = 0
      self.sonar_status = []
      self.arm_torque = []
      self.arm_status = 0
      self.cam360_status = 0
      self.second_cam_status = 0
      self.map_status = 0
      self.ptz_camera = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2di().pack(_x.voltage, _x.orientation, _x.velocity, _x.motor_status))
      length = len(self.sonar_status)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.sonar_status))
      length = len(self.arm_torque)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.arm_torque))
      _x = self
      buff.write(_get_struct_5i().pack(_x.arm_status, _x.cam360_status, _x.second_cam_status, _x.map_status, _x.ptz_camera))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.voltage, _x.orientation, _x.velocity, _x.motor_status,) = _get_struct_f2di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.sonar_status = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.arm_torque = s.unpack(str[start:end])
      _x = self
      start = end
      end += 20
      (_x.arm_status, _x.cam360_status, _x.second_cam_status, _x.map_status, _x.ptz_camera,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2di().pack(_x.voltage, _x.orientation, _x.velocity, _x.motor_status))
      length = len(self.sonar_status)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.sonar_status.tostring())
      length = len(self.arm_torque)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.arm_torque.tostring())
      _x = self
      buff.write(_get_struct_5i().pack(_x.arm_status, _x.cam360_status, _x.second_cam_status, _x.map_status, _x.ptz_camera))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 24
      (_x.voltage, _x.orientation, _x.velocity, _x.motor_status,) = _get_struct_f2di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.sonar_status = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.arm_torque = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 20
      (_x.arm_status, _x.cam360_status, _x.second_cam_status, _x.map_status, _x.ptz_camera,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
_struct_f2di = None
def _get_struct_f2di():
    global _struct_f2di
    if _struct_f2di is None:
        _struct_f2di = struct.Struct("<f2di")
    return _struct_f2di
