// Generated by gencpp from file p2os_msgs/GripState.msg
// DO NOT EDIT!


#ifndef P2OS_MSGS_MESSAGE_GRIPSTATE_H
#define P2OS_MSGS_MESSAGE_GRIPSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace p2os_msgs
{
template <class ContainerAllocator>
struct GripState_
{
  typedef GripState_<ContainerAllocator> Type;

  GripState_()
    : state(0)
    , dir(0)
    , inner_beam(false)
    , outer_beam(false)
    , left_contact(false)
    , right_contact(false)  {
    }
  GripState_(const ContainerAllocator& _alloc)
    : state(0)
    , dir(0)
    , inner_beam(false)
    , outer_beam(false)
    , left_contact(false)
    , right_contact(false)  {
  (void)_alloc;
    }



   typedef uint32_t _state_type;
  _state_type state;

   typedef int32_t _dir_type;
  _dir_type dir;

   typedef uint8_t _inner_beam_type;
  _inner_beam_type inner_beam;

   typedef uint8_t _outer_beam_type;
  _outer_beam_type outer_beam;

   typedef uint8_t _left_contact_type;
  _left_contact_type left_contact;

   typedef uint8_t _right_contact_type;
  _right_contact_type right_contact;





  typedef boost::shared_ptr< ::p2os_msgs::GripState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p2os_msgs::GripState_<ContainerAllocator> const> ConstPtr;

}; // struct GripState_

typedef ::p2os_msgs::GripState_<std::allocator<void> > GripState;

typedef boost::shared_ptr< ::p2os_msgs::GripState > GripStatePtr;
typedef boost::shared_ptr< ::p2os_msgs::GripState const> GripStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p2os_msgs::GripState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p2os_msgs::GripState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::p2os_msgs::GripState_<ContainerAllocator1> & lhs, const ::p2os_msgs::GripState_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.dir == rhs.dir &&
    lhs.inner_beam == rhs.inner_beam &&
    lhs.outer_beam == rhs.outer_beam &&
    lhs.left_contact == rhs.left_contact &&
    lhs.right_contact == rhs.right_contact;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::p2os_msgs::GripState_<ContainerAllocator1> & lhs, const ::p2os_msgs::GripState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace p2os_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::p2os_msgs::GripState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p2os_msgs::GripState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p2os_msgs::GripState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p2os_msgs::GripState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p2os_msgs::GripState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p2os_msgs::GripState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p2os_msgs::GripState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "370eb3507be0ed1043be50a3da3a07c6";
  }

  static const char* value(const ::p2os_msgs::GripState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x370eb3507be0ed10ULL;
  static const uint64_t static_value2 = 0x43be50a3da3a07c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::p2os_msgs::GripState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p2os_msgs/GripState";
  }

  static const char* value(const ::p2os_msgs::GripState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p2os_msgs::GripState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# direction -1 is inward, +1 is outward, 0 is stationary\n"
"uint32 state\n"
"int32 dir\n"
"bool inner_beam\n"
"bool outer_beam\n"
"bool left_contact\n"
"bool right_contact\n"
;
  }

  static const char* value(const ::p2os_msgs::GripState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p2os_msgs::GripState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.dir);
      stream.next(m.inner_beam);
      stream.next(m.outer_beam);
      stream.next(m.left_contact);
      stream.next(m.right_contact);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p2os_msgs::GripState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p2os_msgs::GripState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.state);
    s << indent << "dir: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dir);
    s << indent << "inner_beam: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.inner_beam);
    s << indent << "outer_beam: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.outer_beam);
    s << indent << "left_contact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_contact);
    s << indent << "right_contact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_contact);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P2OS_MSGS_MESSAGE_GRIPSTATE_H
