// Generated by gencpp from file rviz_streamer/Mouse.msg
// DO NOT EDIT!


#ifndef RVIZ_STREAMER_MESSAGE_MOUSE_H
#define RVIZ_STREAMER_MESSAGE_MOUSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rviz_streamer
{
template <class ContainerAllocator>
struct Mouse_
{
  typedef Mouse_<ContainerAllocator> Type;

  Mouse_()
    : header()
    , x(0)
    , y(0)
    , buttons()  {
    }
  Mouse_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0)
    , y(0)
    , buttons(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _buttons_type;
  _buttons_type buttons;





  typedef boost::shared_ptr< ::rviz_streamer::Mouse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rviz_streamer::Mouse_<ContainerAllocator> const> ConstPtr;

}; // struct Mouse_

typedef ::rviz_streamer::Mouse_<std::allocator<void> > Mouse;

typedef boost::shared_ptr< ::rviz_streamer::Mouse > MousePtr;
typedef boost::shared_ptr< ::rviz_streamer::Mouse const> MouseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rviz_streamer::Mouse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rviz_streamer::Mouse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rviz_streamer::Mouse_<ContainerAllocator1> & lhs, const ::rviz_streamer::Mouse_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.buttons == rhs.buttons;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rviz_streamer::Mouse_<ContainerAllocator1> & lhs, const ::rviz_streamer::Mouse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rviz_streamer

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rviz_streamer::Mouse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rviz_streamer::Mouse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rviz_streamer::Mouse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rviz_streamer::Mouse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_streamer::Mouse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rviz_streamer::Mouse_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rviz_streamer::Mouse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "172513ca8a49df1d02eb2a66cecb8b4f";
  }

  static const char* value(const ::rviz_streamer::Mouse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x172513ca8a49df1dULL;
  static const uint64_t static_value2 = 0x02eb2a66cecb8b4fULL;
};

template<class ContainerAllocator>
struct DataType< ::rviz_streamer::Mouse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rviz_streamer/Mouse";
  }

  static const char* value(const ::rviz_streamer::Mouse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rviz_streamer::Mouse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 x\n"
"uint32 y\n"
"int32[] buttons\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::rviz_streamer::Mouse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rviz_streamer::Mouse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.buttons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mouse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rviz_streamer::Mouse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rviz_streamer::Mouse_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
    s << indent << "buttons[]" << std::endl;
    for (size_t i = 0; i < v.buttons.size(); ++i)
    {
      s << indent << "  buttons[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.buttons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RVIZ_STREAMER_MESSAGE_MOUSE_H
